# Generated by Django 4.2.6 on 2023-10-25 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_variacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variacao',
            options={'verbose_name': 'Variação', 'verbose_name_plural': 'Variações'},
        ),
    ]
